AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sistema de Feedback de Restaurantes com Quarkus Lambda

Parameters:
  DBHost:
    Type: String
    Description: RDS PostgreSQL Endpoint
  DBPort:
    Type: String
    Default: '5432'
  DBName:
    Type: String
    Default: feedback_db
  DBUsername:
    Type: String
    Default: postgres
  DBPassword:
    Type: String
    NoEcho: true
    Description: Database Password

Globals:
  Function:
    Runtime: java21
    Timeout: 30
    MemorySize: 512
    Environment:
      Variables:
        DB_HOST: !Ref DBHost
        DB_PORT: !Ref DBPort
        DB_NAME: !Ref DBName
        DB_USERNAME: !Ref DBUsername
        DB_PASSWORD: !Ref DBPassword

Resources:
  # SQS Queue para notificações urgentes
  NotificacaoUrgenciaQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: notificacao-urgencia-queue
      VisibilityTimeout: 60
      MessageRetentionPeriod: 345600  # 4 dias

  # SNS Topic para alertas
  UrgenciaAlertTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: urgencia-topic
      DisplayName: Sistema de Feedback - Alertas de Urgência

  # Lambda 1: Receber e Processar Feedback
  ReceberFeedbackFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: receber-feedback
      Handler: lambda.fase4.lambda.ReceberFeedbackHandler::handleRequest
      CodeUri: target/function.zip
      Description: Recebe e processa feedback de clientes
      Environment:
        Variables:
          SQS_NOTIFICACAO_URL: !GetAtt NotificacaoUrgenciaQueue.QueueUrl
          SNS_URGENCIA_ARN: !Ref UrgenciaAlertTopic
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !GetAtt NotificacaoUrgenciaQueue.QueueName
        - CloudWatchPutMetricPolicy: {}
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /feedback
            Method: POST

  # Lambda 2: Enviar Notificações da Fila SQS
  EnviarNotificacaoFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: enviar-notificacao
      Handler: lambda.fase4.lambda.EnviarNotificacaoHandler::handleRequest
      CodeUri: target/function.zip
      Description: Processa notificações urgentes da fila SQS
      Environment:
        Variables:
          SNS_URGENCIA_ARN: !Ref UrgenciaAlertTopic
      Policies:
        - SQSPollerPolicy:
            QueueName: !GetAtt NotificacaoUrgenciaQueue.QueueName
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt UrgenciaAlertTopic.TopicName
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt NotificacaoUrgenciaQueue.Arn
            BatchSize: 10

  # Lambda 3: Gerar Relatório Semanal
  GerarRelatorioFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: gerar-relatorio
      Handler: lambda.fase4.lambda.GerarRelatorioHandler::handleRequest
      CodeUri: target/function.zip
      Description: Gera relatório semanal automaticamente
      Timeout: 60
      MemorySize: 1024
      Environment:
        Variables:
          SNS_URGENCIA_ARN: !Ref UrgenciaAlertTopic
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt UrgenciaAlertTopic.TopicName
      Events:
        ScheduleEvent:
          Type: Schedule
          Properties:
            Schedule: cron(0 9 ? * MON *)  # Toda segunda-feira às 9h UTC
            Description: Trigger semanal para geração de relatório

  # API Gateway Log Group
  ApiAccessLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/apigateway/feedback-api
      RetentionInDays: 7

Outputs:
  ApiUrl:
    Description: URL do API Gateway para enviar feedback
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/feedback'

  QueueUrl:
    Description: URL da fila SQS para notificações
    Value: !GetAtt NotificacaoUrgenciaQueue.QueueUrl

  TopicArn:
    Description: ARN do tópico SNS para alertas
    Value: !Ref UrgenciaAlertTopic

  ReceberFeedbackArn:
    Description: ARN da função Lambda Receber Feedback
    Value: !GetAtt ReceberFeedbackFunction.Arn

  EnviarNotificacaoArn:
    Description: ARN da função Lambda Enviar Notificação
    Value: !GetAtt EnviarNotificacaoFunction.Arn

  GerarRelatorioArn:
    Description: ARN da função Lambda Gerar Relatório
    Value: !GetAtt GerarRelatorioFunction.Arn

